# CMake generated Testfile for 
# Source directory: /root/projects/minishell/test_src
# Build directory: /root/projects/minishell/test_src
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ms_parse_tokens "/root/projects/minishell/test_src/test_ms_parse_tokens")
set_tests_properties(ms_parse_tokens PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/root/projects/minishell/test_src/CMakeLists.txt;111;add_test;/root/projects/minishell/test_src/CMakeLists.txt;0;")
add_test(ms_echo "/root/projects/minishell/test_src/test_ms_echo")
set_tests_properties(ms_echo PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/root/projects/minishell/test_src/CMakeLists.txt;111;add_test;/root/projects/minishell/test_src/CMakeLists.txt;0;")
add_test(ms_env "/root/projects/minishell/test_src/test_ms_env")
set_tests_properties(ms_env PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/root/projects/minishell/test_src/CMakeLists.txt;111;add_test;/root/projects/minishell/test_src/CMakeLists.txt;0;")
add_test(ms_exit "/root/projects/minishell/test_src/test_ms_exit")
set_tests_properties(ms_exit PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/root/projects/minishell/test_src/CMakeLists.txt;111;add_test;/root/projects/minishell/test_src/CMakeLists.txt;0;")
add_test(ms_export "/root/projects/minishell/test_src/test_ms_export")
set_tests_properties(ms_export PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/root/projects/minishell/test_src/CMakeLists.txt;111;add_test;/root/projects/minishell/test_src/CMakeLists.txt;0;")
add_test(ms_pwd "/root/projects/minishell/test_src/test_ms_pwd")
set_tests_properties(ms_pwd PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/root/projects/minishell/test_src/CMakeLists.txt;111;add_test;/root/projects/minishell/test_src/CMakeLists.txt;0;")
add_test(ms_unset "/root/projects/minishell/test_src/test_ms_unset")
set_tests_properties(ms_unset PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/root/projects/minishell/test_src/CMakeLists.txt;111;add_test;/root/projects/minishell/test_src/CMakeLists.txt;0;")
add_test(check_testunit_template "/root/projects/minishell/test_src/check_testunit_template")
set_tests_properties(check_testunit_template PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/root/projects/minishell/test_src/CMakeLists.txt;111;add_test;/root/projects/minishell/test_src/CMakeLists.txt;0;")
add_test(ms_expand_args "/root/projects/minishell/test_src/test_ms_expand_args")
set_tests_properties(ms_expand_args PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/root/projects/minishell/test_src/CMakeLists.txt;111;add_test;/root/projects/minishell/test_src/CMakeLists.txt;0;")
add_test(ms_env_add_back "/root/projects/minishell/test_src/test_ms_env_add_back")
set_tests_properties(ms_env_add_back PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/root/projects/minishell/test_src/CMakeLists.txt;111;add_test;/root/projects/minishell/test_src/CMakeLists.txt;0;")
add_test(ms_env_create_node "/root/projects/minishell/test_src/test_ms_env_create_node")
set_tests_properties(ms_env_create_node PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/root/projects/minishell/test_src/CMakeLists.txt;111;add_test;/root/projects/minishell/test_src/CMakeLists.txt;0;")
add_test(ms_get_env_value "/root/projects/minishell/test_src/test_ms_get_env_value")
set_tests_properties(ms_get_env_value PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/root/projects/minishell/test_src/CMakeLists.txt;111;add_test;/root/projects/minishell/test_src/CMakeLists.txt;0;")
add_test(ms_get_envp "/root/projects/minishell/test_src/test_ms_get_envp")
set_tests_properties(ms_get_envp PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/root/projects/minishell/test_src/CMakeLists.txt;111;add_test;/root/projects/minishell/test_src/CMakeLists.txt;0;")
add_test(ms_get_user_input "/root/projects/minishell/test_src/test_ms_get_user_input")
set_tests_properties(ms_get_user_input PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/root/projects/minishell/test_src/CMakeLists.txt;111;add_test;/root/projects/minishell/test_src/CMakeLists.txt;0;")
add_test(ms_getenv "/root/projects/minishell/test_src/test_ms_getenv")
set_tests_properties(ms_getenv PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/root/projects/minishell/test_src/CMakeLists.txt;111;add_test;/root/projects/minishell/test_src/CMakeLists.txt;0;")
add_test(ms_init_env "/root/projects/minishell/test_src/test_ms_init_env")
set_tests_properties(ms_init_env PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/root/projects/minishell/test_src/CMakeLists.txt;111;add_test;/root/projects/minishell/test_src/CMakeLists.txt;0;")
add_test(ms_init_shell "/root/projects/minishell/test_src/test_ms_init_shell")
set_tests_properties(ms_init_shell PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/root/projects/minishell/test_src/CMakeLists.txt;111;add_test;/root/projects/minishell/test_src/CMakeLists.txt;0;")
add_test(ms_init_std_signal "/root/projects/minishell/test_src/test_ms_init_std_signal")
set_tests_properties(ms_init_std_signal PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/root/projects/minishell/test_src/CMakeLists.txt;111;add_test;/root/projects/minishell/test_src/CMakeLists.txt;0;")
add_test(ms_stop_std_signal "/root/projects/minishell/test_src/test_ms_stop_std_signal")
set_tests_properties(ms_stop_std_signal PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/root/projects/minishell/test_src/CMakeLists.txt;111;add_test;/root/projects/minishell/test_src/CMakeLists.txt;0;")
add_test(ms_syntax_error "/root/projects/minishell/test_src/test_ms_syntax_error")
set_tests_properties(ms_syntax_error PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/root/projects/minishell/test_src/CMakeLists.txt;111;add_test;/root/projects/minishell/test_src/CMakeLists.txt;0;")
add_test(lst_tokens "/root/projects/minishell/test_src/test_lst_tokens")
set_tests_properties(lst_tokens PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/root/projects/minishell/test_src/CMakeLists.txt;111;add_test;/root/projects/minishell/test_src/CMakeLists.txt;0;")
add_test(ms_tokenize "/root/projects/minishell/test_src/test_ms_tokenize")
set_tests_properties(ms_tokenize PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/root/projects/minishell/test_src/CMakeLists.txt;111;add_test;/root/projects/minishell/test_src/CMakeLists.txt;0;")
add_test(tokenize_frame "/root/projects/minishell/test_src/test_tokenize_frame")
set_tests_properties(tokenize_frame PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/root/projects/minishell/test_src/CMakeLists.txt;111;add_test;/root/projects/minishell/test_src/CMakeLists.txt;0;")
add_test(tokenize_operator "/root/projects/minishell/test_src/test_tokenize_operator")
set_tests_properties(tokenize_operator PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/root/projects/minishell/test_src/CMakeLists.txt;111;add_test;/root/projects/minishell/test_src/CMakeLists.txt;0;")
add_test(tokenize_word "/root/projects/minishell/test_src/test_tokenize_word")
set_tests_properties(tokenize_word PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/root/projects/minishell/test_src/CMakeLists.txt;111;add_test;/root/projects/minishell/test_src/CMakeLists.txt;0;")
