name: CI

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          clean: true

      # Build libft
      - name: Build libft
        run: |
          cd lib/libft
          make

      # Build libgc
      - name: Build libgc
        run: |
          cd lib/libgc
          make

      # Clean Build Directory
     - name: Clean Build Directories
       run: |
        rm -rf build/
        rm -rf test_src/build/
        rm -rf test_src/CMakeCache.txt
        rm -rf test_src/CMakeFiles/

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y check

      # Configure CMake
      - name: Configure CMake
        run: cmake -S test_src -B test_src/build -U "*"

      # Build
      - name: Build
        run: cmake --build test_src/build

      # Run Tests
      - name: Run Tests
        run: |
          cd test_src/build
          ctest --output-on-failure

