name: Integrated Tests

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: jeportie/vjej:latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          clean: true

      # Map workspace to expected path
      - name: Adjust Workspace Path
        run: |
          mkdir -p /root/projects
          ln -s /github/workspace /root/projects/minishell

      # Build libft
      - name: Build libft
        run: |
          cd /root/projects/minishell/lib/libft
          make

      # Build libgc
      - name: Build libgc
        run: |
          cd /root/projects/minishell/lib/libgc
          make

      # Clean Build Directory
      - name: Clean Build Directory
        run: rm -rf /root/projects/minishell/test_src/build/

      # Build and Run Tests
      - name: Build Tests
        run: |
          cd /root/projects/minishell/test_src
          mkdir build
          cd build
          cmake ..
          make

      # Run Tests
      - name: Run Tests
        run: |
          cd test_src/build
          ctest --output-on-failure

