name: Integrated Tests

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: jeportie/vjej:latest
      options: >
        --workdir /root/projects/minishell
        --volume ${GITHUB_WORKSPACE}:/root/projects/minishell

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          clean: true

      # Build libft
      - name: Build libft
        run: |
          cd lib/libft
          make

      # Build libgc
      - name: Build libgc
        run: |
          cd lib/libgc
          make

      # Clean Build Directory
      - name: Clean Build Directory
        run: rm -rf test_src/build/

      # Build and Run Tests
      - name: Build Tests
        run: |
          cd test_src
          mkdir build
          cd build
          cmake ..
          make

      # Build and Run Tests
      - name: Run Tests
        run: |
          cd test_src
          ctest --output-on-failure

