name: Integrated Tests

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: jeportie/vjej:latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          clean: true

      # Build libft
      - name: Build libft
        run: |
          cd lib/libft
          make
        working-directory: /github/workspace

      # Build libgc
      - name: Build libgc
        run: |
          cd lib/libgc
          make
        working-directory: /github/workspace

      # Clean Build Directory
      - name: Clean Build Directory
        run: rm -rf test_src/build/
        working-directory: /github/workspace

      # Build and Run Tests
      - name: Build and Run Tests
        run: |
          cd test_src
          mkdir build
          cd build
          cmake ..
          make
          ctest --output-on-failure
        working-directory: /github/workspace

