name: Minishell Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: jeportie/vjej:latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          clean: true

      # Build libft
      - name: Build libft
        run: |
          cd lib/libft
          make

      # Build libgc
      - name: Build libgc
        run: |
          cd lib/libgc
          make

      # Build Minishell (optional)
      # - name: Build Minishell
      #  run: |
      #    make test

      # Build Test Suite
      - name: Build Test Suite
        run: |
          cd test_minishell
          mkdir -p build
          cd build
          cmake ..
          make

      # Run Tests
      - name: Run Tests
        run: |
          cd test_integrated
          ./run_test.sh
